sudo: false
language: generic
matrix:
  include:
  - os: linux
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
  timeout: 3600
before_install:
- travis_wait 45 bash ./utilities/travis_setup.sh
- export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
script:
- latexmk -pdf -interaction=nonstopmode -halt-on-error presentation.tex
after_success: 
deploy:
  provider: releases
  api_key:
    secure: MZ7h+5s06xZuUINzzg7AKiCRZV4YdI0USXenYEmVLgOHsy+NbJZf7znxwc5qv61QIy6bzrCjeh8Lky77223S7y6eJHnT7DOcxxdl2iC44URbR3CppdJBVuxDn+Qub6F33bq1Mi7zAFj60WJPJOp9XEJyJvNc7zC9ZgdExT88y7gRqnNhj9ExBBHsRZAkWzlWYDsyk7Sj3lWjNGh64Nquxyrik2Rket5ywth7NMzJ4c3Cc84BWRonePYhsxXSO+DFF+DfXd+6ELPVTGrC0Wl/d6gJ/hAjOxh8b6xeTdqC3Rc0R6TYh+Omy4EZYIV9nz7Q5dnxblN7kyYQ0Oz6eCIAL9s90h9bHisLdWxkN7a/ZogxIrv14iBWFgJU5CjAyDMLNpU7tHofw8nckbiKgZCW5so6XgmY2xtl/nyhXNSt3bjHMzf6x19zz0KrVZqTAWtNwz6+hO8vPgXcJgVJmSpqAJaxLGYUTf5xka9nVEVtQ9CAg5xqY8a4YsPP9Z+zGAEonbIhlbLbv9BGj1xyiudBV/R1GgtOGdQb/O89ArDHMfH+Id4jVJzNUUutzR48OFdHHy66ppWNyr7+X/MCBhsyCvD1wjF+ZpQeg/alnFYEMSJCRX/O9P5AOMCZ3gAs0U2ssODTfyd2WmEX5IzhnerRnM9Z7ZbkZZyZMvD9ZJ+0WT0=
  file: presentation.pdf
  skip_cleanup: true
  on:
    repo: skulumani/2018_aas_presentation
    tags: true
